version: '3'

x-omnistrate-integrations:
  - omnistrateLogging:
  - omnistrateMetrics:

x-omnistrate-load-balancer:
  https:
    - name: Dashboard
      description: L7 Load Balancer for the Ray Head Node Dashboard
      paths:
        - associatedResourceKey: rayhead
          path: /
          backendPort: 8265

services:
  raycluster:
    image: omnistrate/noop
    depends_on:
      - rayhead
      - rayworker
    x-omnistrate-api-params:
      - key: numGPUWorkerReplicas
        description: Number of GPU worker replicas
        name: Number of GPU-powered worker Replicas
        type: Float64
        modifiable: true
        required: false
        export: true
        defaultValue: "0"
        # parameterDependencyMap:
        #   raygpuworker: numReplicas
      - key: gpuWorkerInstanceType
        description: GPU worker instance type
        name: GPU Worker Instance Type
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: "g4dn.xlarge"
        # parameterDependencyMap:
        #   raygpuworker: instanceType
      - key: cpuWorkerInstanceType
        description: CPU worker instance type
        name: CPU Worker Instance Type
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: "t3.small"
        parameterDependencyMap:
          rayworker: instanceType
  rayhead:
    x-omnistrate-compute:
      replicaCount: 1
      instanceTypes:
        - cloudProvider: aws
          apiParam: instanceType
        - cloudProvider: gcp
          apiParam: instanceType
    x-omnistrate-mode-internal: true
    build:
      context: ./rayhead
      dockerfile: Dockerfile
    command: /bin/sh -c '/start.sh'
    ports:
      - "8265:8265" # Ray Dashboard
      - "6379:6379" # Ray Redis
      - "10001:10001" # Ray Client
    # environment:
    #   RAY_USE_TLS: "0"
    #   RAY_TLS_SERVER_CERT: "/etc/tls/tls.crt"
    #   RAY_TLS_SERVER_KEY: "/etc/tls/tls.key"
    #   RAY_TLS_CA_CERT: "/etc/tls/tls-combined.pem"
    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type
        name: Instance Type
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: "t3.large"
  rayworker:
    x-omnistrate-compute:
      instanceTypes:
        - cloudProvider: aws
          apiParam: instanceType
        - cloudProvider: gcp
          apiParam: instanceType
    x-omnistrate-mode-internal: true
    build:
      context: ./rayworker
      dockerfile: Dockerfile
    command: /bin/sh -c '/start.sh'
    x-omnistrate-capabilities:
      autoscaling:
        maxReplicas: 5
        minReplicas: 1
        idleMinutesBeforeScalingDown: 2
        idleThreshold: 20
        overUtilizedMinutesBeforeScalingUp: 3
        overUtilizedThreshold: 80
      enableMultiZone: true
    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type
        name: Instance Type
        type: String
        modifiable: true
        required: true
        export: true
  # raygpuworker:
  #   x-omnistrate-compute:
  #     replicaCountAPIParam: numReplicas
  #     instanceTypes:
  #       - cloudProvider: aws
  #         apiParam: instanceType
  #       - cloudProvider: gcp
  #         apiParam: instanceType
  #   x-omnistrate-mode-internal: true
  #   x-omnistrate-capabilities:
  #     enableMultiZone: true
  #   build:
  #     context: ./raygpuworker
  #     dockerfile: Dockerfile
  #   command: /bin/sh -c '/start.sh'
  #   x-omnistrate-api-params:
  #     - key: instanceType
  #       description: Instance Type
  #       name: Instance Type
  #       type: String
  #       modifiable: true
  #       required: true
  #       export: true
  #     - key: numReplicas
  #       description: Number of Replicas
  #       name: Number of Replicas
  #       type: Float64
  #       modifiable: true
  #       required: true
  #       export: true
  hello-world:
    build:
      context: ./jobs/hello-world
      dockerfile: Dockerfile
    environment:
      RAY_ADDRESS: "ray://{{ $var.rayClusterAddress }}:10001"
      SCRIPT_PATH: "submit_job.py"
    privileged: true
    volumes:
      - source: ./jobs/hello-world
        target: /app
        type: bind
      - source: ./tmp
        target: /tmp
        type: bind
    x-omnistrate-compute:
      replicaCountApiParam: numReplicas
      instanceTypes:
        - cloudProvider: aws
          name: t3.small
        - cloudProvider: gcp
          name: e2-small
    x-omnistrate-job-config:
      backoffLimit: 0
      activeDeadlineSeconds: 3600
    x-omnistrate-api-params:
      - key: rayClusterAddress
        description: Ray Cluster Address
        name: Ray Cluster Address
        type: String
        modifiable: true
        required: true
        export: true
      - key: numReplicas
        description: Number of Replicas
        name: Number of Replicas
        type: Float64
        modifiable: true
        required: false
        export: true
        defaultValue: "1"
x-omnistrate-image-registry-attributes:
  ghcr.io:
    auth:
      password: ${{ secrets.GitHubPAT }}
      username: aloknikhil
