name: Bulid from repo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
       
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:    
            registry: ghcr.io
            username: api
            password: ${{ github.token }}

        - name: Setup Omnistrate CTL
          uses: omnistrate-oss/setup-omnistrate-ctl@v1
          with:
            email: ${{ secrets.OMNISTRATE_USERNAME }}
            password: ${{ secrets.OMNISTRATE_PASSWORD }}

        - name: Build and Deploy with Omnistrate CLI
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_TOKEN: ${{ github.token }}
          run: omctl build-from-repo -f spec-cluster.yaml --service-name Ray --username ${{ secrets.OMNISTRATE_USERNAME }} --password ${{ secrets.OMNISTRATE_PASSWORD }} --image-name omnistrate/ray:latest --image-tag latest --build-args GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} --build-args GITHUB_USER=${{ github.actor }} --build-args GITHUB_REPO=${{ github.repository }} --build-args GITHUB_SHA=${{ github.sha }} --build-args GITHUB_REF=${{ github.ref_name }} --build-args GITHUB_RUN_ID=${{ github.run_id }} --build-args GITHUB_RUN_NUMBER=${{ github.run_number }}