name: Build from repo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: false

permissions:
  contents: read
  packages: write  # Required for GitHub Packages
  id-token: write  # Required for "Trusted Publishing" on npm

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
       
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Omnistrate CTL
          uses: omnistrate-oss/setup-omnistrate-ctl@v1
          with:
            email: ${{ secrets.OMNISTRATE_USERNAME }}
            password: ${{ secrets.OMNISTRATE_PASSWORD }}

        - name: Build and Deploy with Omnistrate CLI (dry run)
          if : github.event_name == 'pull_request'
          env:
            GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          run: | 
            omctl build-from-repo -f spec-jobs-mt.yaml --service-name Ray --skip-publishing

        - name: Build and Deploy with Omnistrate CLI
          if : github.event_name != 'pull_request'
          env:
            GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          run: | 
            omctl build-from-repo -f spec-jobs-mt.yaml --service-name Ray